// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewut5zCU0QkHdMMajA8ggp4UD4D8TyC0',
    appId: '1:913425052522:web:32a717a7296373466aeb13',
    messagingSenderId: '913425052522',
    projectId: 'rlts-jnt',
    authDomain: 'rlts-jnt.firebaseapp.com',
    storageBucket: 'rlts-jnt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEV43dBv5tnh6jcXdsG6LlZ3r5zEYkUxI',
    appId: '1:913425052522:android:2abb7c648ed714656aeb13',
    messagingSenderId: '913425052522',
    projectId: 'rlts-jnt',
    storageBucket: 'rlts-jnt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMP9IdrUx6GXQOI7-JjcF2ST2biphU0Rs',
    appId: '1:913425052522:ios:fdf7574fcfbff2116aeb13',
    messagingSenderId: '913425052522',
    projectId: 'rlts-jnt',
    storageBucket: 'rlts-jnt.appspot.com',
    iosBundleId: 'com.example.appdois',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMP9IdrUx6GXQOI7-JjcF2ST2biphU0Rs',
    appId: '1:913425052522:ios:fdf7574fcfbff2116aeb13',
    messagingSenderId: '913425052522',
    projectId: 'rlts-jnt',
    storageBucket: 'rlts-jnt.appspot.com',
    iosBundleId: 'com.example.appdois',
  );

}